---

sudo: required

language: node_js

node_js:
  - 4

python:
  - 3.4

cache:
  directories:
    - node_modules

before_script:
  - sudo pip install transifex-client

script:
  - echo $TX_PASSWORD >> .transifexrc_on_travis
  - mv .transifexrc_on_travis .transifexrc
  - npm run build
  - npm run test

before_deploy:
  - cd public

deploy:
  provider: npm
  email: frank@cozycloud.cc
  api_key:
    secure: Ci6JiHjsEQPUHLKVuWvfMLvk/Obs3vqMMig91loV/JPgrVInX6s4YSmeKnxMjidAIWjwnqEVJrNUn9v2kvxTUI2/ifAapnq9XtxNV8rhn8ZLku3bUvR/8rRvsIgDXvl4ziNT7l0zN44WzoZNwhNtON3F5OIwiBAc3BQjnYBIbao8wNb4v3KXyuS8r/ABcVx5smAnoGbpCj8zTkCzfj0liPwWNwQy1anu6r8BWNFCaviCwLT1JbfsxFliFMBdn5N9fETToN+EMmai7oZEFgf8lPXILl5aQl75+Xm7LloqD+U2S+cpbQyze34WFitW/t9FD5ZRD4vlLps7rlAIju3ErbORzHZRLP3saf1fH7lp0Ax1jMjpcJV20PoF3z7NoyDaeg3bkKagG8Qmf1wbCKrBKjKxPcolVizA+vmyc15AjQTWp4Dcs48OhQIc9Fcs7YjZ97QYYTziAvG93fgqh7XSs4JFLLtXTRG1WkCKaYBOgHAaTOBFHiRSr9D+zdU6VwE++VJuI2T2qXTAcTyWZwygJotKyfHCXIjNirtJ9Ke8t325rSqSCSTGnN59nHXDsLA2qEq2O4unfosKY6TYvBD/RQaLtO2tyeDWu2TTCJ95MqJPjYvOBgQDRG7meOp1gX2SDwx/GAtekun6F6kxBLdf8tyqKnQhu1UIgBvziTlN9a8=
  on:
    branch: master
    tags: true
    repo: cozy-labs/cozy-music

env:
  global:
    secure: CA0WhO3Gnx1jjQT1K9l8ULs3xU5pvdFr59kKESXTRp6xRhCGqW8n5fWSZ8YPr8NHAhq4BrwAlDtjbtsofau3bHBSIMvSwLV10mmya9LLA/3CxjBthpv8vPAf+RQH7ZLR61HQJJ+9f6oDCAW/LxhVUrYSlDsyRRVsmty3svObDEHF6o3SWK2Ls87uLdkBZuOgJanWom20MUGzERmvJWso8gJo5boSCNf/kvmXOZorpyshzl+CkhplIHE5vEv+ki2M9e3wOV4tUbLPbos9CD70VyQ09bnmimFsJOSWdbrodt0wBxIQSt59UtINudK9/pPjPFoDBZuqrHQomiJQSuLHLjdx9rtNGLscx5a/1+eZGeLuI4r2nm0zp8YJHZS3XiaJc/1d29uLCj5JxutHk8vWdTjQZKdQN3YkUdXCs3xzQpiBDG/1JpBs/20P9FfRS/lIEgkaWpz1/otZ2w9FlOZYgMPTJcMSUFGdY8YD0jvpwD+SXgFDOxBL02ExcIL4dIe8+f/XMyjXROcMJDsdD9p/DG9HZ6fIv4jkbzU9vdqDtMevXUXateIazdRXuqnjEM/4AN0iJ4j0kb5cAH5YWWbx7MwFnp7oWWnV30wy7bNIlhqeBAsXma8YEqjSjF+7PgubEzuoxiSJp/Pkt6npU4Rn62TdArH8F/XsNN05KKJSK3w=
